// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy6W7tRyoL30SnjCkwlTGrlnNWS6TDaX8',
    appId: '1:109085937956:web:a0fb8fdb64d687934763b1',
    messagingSenderId: '109085937956',
    projectId: 'chat-app-b2cd6',
    authDomain: 'chat-app-b2cd6.firebaseapp.com',
    storageBucket: 'chat-app-b2cd6.firebasestorage.app',
    measurementId: 'G-214VP1ENJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuMmo7pxPRlQYDmcPtBzmK3PgmYKXaPSs',
    appId: '1:109085937956:android:44a83a817f0f4cc44763b1',
    messagingSenderId: '109085937956',
    projectId: 'chat-app-b2cd6',
    storageBucket: 'chat-app-b2cd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjWaST4xSiY0jhDCzH0f2aMFXAloEVqCA',
    appId: '1:109085937956:ios:bd5f15578e15fbd24763b1',
    messagingSenderId: '109085937956',
    projectId: 'chat-app-b2cd6',
    storageBucket: 'chat-app-b2cd6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjWaST4xSiY0jhDCzH0f2aMFXAloEVqCA',
    appId: '1:109085937956:ios:bd5f15578e15fbd24763b1',
    messagingSenderId: '109085937956',
    projectId: 'chat-app-b2cd6',
    storageBucket: 'chat-app-b2cd6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy6W7tRyoL30SnjCkwlTGrlnNWS6TDaX8',
    appId: '1:109085937956:web:fcdf5fca9b3bede94763b1',
    messagingSenderId: '109085937956',
    projectId: 'chat-app-b2cd6',
    authDomain: 'chat-app-b2cd6.firebaseapp.com',
    storageBucket: 'chat-app-b2cd6.firebasestorage.app',
    measurementId: 'G-XJKTJEQL55',
  );
}
